preserve_hierarchy: true


files:
  - source: /*.csv
    dest: "/conf/**/%file_name%.csv"
    translation: /GET%two_letters_code%/%original_file_name%
    type: "csv"
    first_line_contains_header: 1
    scheme: 'identifier,context,source_or_translation'
  - source: /*.csv
    translation: /get/%two_letters_code%/%original_file_name%
    multilingual_spreadsheet: 1
    first_line_contains_header: 1
    scheme: 'identifier,context,source_phrase,es-ES,fr,max_length'
    translation_replace: {
      " Traducción 2": "Traducción 22" 
