preserve_hierarchy: true


files:
  - source: /black.csv
    dest: "/conf/%file_name%.csv"
    translation: /%file_name%.%locale%.csv
    type: "csv"
    first_line_contains_header: 1
    scheme: 'identifier,context,source_or_translation'
    translation_replace:
      ".en-US": "" 
  - source: /Multilingual_spreadsheet_sample.csv
    translation: %original_file_name%
    multilingual_spreadsheet: 1
    first_line_contains_header: 1
    scheme: 'identifier,context,source_phrase,es-ES,fr,max_length'

